name: swe_simulator
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - _x86_64-microarch-level=3=3_skylake
  - attr=2.5.2=h39aace5_0
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cpython=3.14.2=py314hd8ed1ab_101
  - fftw=3.3.10=mpi_openmpi_h76e6d66_11
  - hdf5=1.14.6=mpi_openmpi_h106f004_5
  - hypre=2.32.0=mpi_openmpi_h398ea61_1
  - icu=78.2=h33c6efd_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libaec=1.1.5=h088129d_0
  - libamd=3.3.3=haaf9dc3_7100102
  - libblas=3.11.0=7_hc00574d_netlib
  - libbtf=2.3.2=h32481e8_7100102
  - libcamd=3.3.3=h32481e8_7100102
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=7_h8e06fc2_netlib
  - libccolamd=3.3.4=h32481e8_7100102
  - libcholmod=5.3.1=h59ddab4_7100102
  - libcolamd=3.3.4=h32481e8_7100102
  - libcurl=8.18.0=h4e3cde8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libfabric=2.4.0=ha770c72_1
  - libfabric1=2.4.0=h8f87c3e_1
  - libffi=3.5.2=h3435931_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - libhwloc=2.12.2=default_hafda6a7_1000
  - libiconv=1.18=h3b78370_2
  - libklu=2.3.5=hf24d653_7100102
  - liblapack=3.11.0=7_h8876d29_netlib
  - liblzma=5.8.2=hb03c661_0
  - libmpdec=4.0.0=hb03c661_1
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libpmix=5.0.8=h9b03745_3
  - libptscotch=7.0.10=int32_ha94cade_2
  - libscotch=7.0.10=int32_h865694f_2
  - libspqr=4.3.4=h852d39f_7100102
  - libsqlite=3.51.2=hf4e2dac_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libsuitesparseconfig=7.10.1=h92d6892_7100102
  - libsystemd0=258.3=h6569c3e_0
  - libudev1=258.3=h6569c3e_0
  - libumfpack=6.3.5=heb53515_7100102
  - libuuid=2.41.3=h5347b49_0
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libzlib=1.3.1=hb9d3cd8_2
  - metis=5.1.0=hd0bcaf9_1007
  - mpi=1.0.1=openmpi
  - mumps-include=5.8.1=h158ef2a_4
  - mumps-mpi=5.8.1=hcc12995_4
  - ncurses=6.5=h2d0b736_3
  - numpy=2.4.1=py314h2b28147_0
  - openmpi=5.0.8=h611b0e2_111
  - openssl=3.6.1=h35e630c_1
  - parmetis=4.0.3=h02de7a9_1007
  - petsc=3.24.3=real_h326748a_1
  - petsc4py=3.24.3=np2py310h90edcb8_0
  - pip=25.3=pyh145f28c_0
  - python=3.14.2=h32b2ec7_101_cp314
  - python-gil=3.14.2=h4df99d1_101
  - python_abi=3.14=8_cp314
  - rdma-core=61.0=h192683f_0
  - readline=8.3=h853b02a_0
  - scalapack=2.2.0=hf7e2fd8_5
  - superlu=7.0.1=h8f6e6c4_0
  - superlu_dist=9.1.0=h3349319_0
  - tk=8.6.13=noxft_h366c992_103
  - tzdata=2025c=hc9c84f9_1
  - ucc=1.6.0=hcedbda0_2
  - ucx=1.20.0=hf72d326_1
  - yaml=0.2.5=h280c20c_3
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - cartopy==0.25.0
      - certifi==2026.1.4
      - clawpack==5.14.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.61.1
      - kiwisolver==1.4.9
      - matplotlib==3.10.8
      - mpi4py==4.1.1
      - packaging==26.0
      - pandas==3.0.0
      - pillow==12.1.0
      - pyparsing==3.3.2
      - pyproj==3.7.2
      - pyshp==3.0.3
      - python-dateutil==2.9.0.post0
      - scipy==1.17.0
      - shapely==2.1.2
      - six==1.17.0
      - xarray==2025.12.0
prefix: /home/xioeng/anaconda3/envs/swe_simulator
